---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - autojump
  - git
  - tree
  - httpie
  - curl
  - wget
  - kubectl
  - kubernetes-helm
  - zsh
  - go
  - vim
  - neovim
  - ag
  - ctags
  - terraform
  - yarn
  - tmux
  - dinghy
  - awscli
  - yarn
  - php71

# homebrew cask applications
cask_applications:
  - google-chrome
  - slack
  - sublime-text
  - iterm2
  - caffeine
  - docker
  - minikube
  - 1password
  - alfred
  - virtualbox
  - skype
  - sqlectron
  - the-unarchiver
  - rambox
  - phpstorm
  - webstorm
  - evernote

downloads: {}
